# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
  module Fluorite
    module Docs
      module D_PRESETS
        # # Smart Conversion Presets
        #
        # Fluorite includes pre-calculated, battle-tested presets for frequent media conversion tasks.
        # These presets encapsulate the complex mathematical calculations and multi-pass filtergraphs
        # required for professional-grade video encoding.
        #
        # ### Executive Summary & Key Topics
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Topic</th>
        #       <th>Method / Anchor</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><strong>Discord File Size Optimization</strong></td>
        #       <td><code>.topic_01_discord_budgeting</code></td>
        #       <td>Guaranteeing uploads fit under Discord limits without rejection.</td>
        #     </tr>
        #     <tr>
        #       <td><strong>2-Pass Palette GIF Generation</strong></td>
        #       <td><code>.topic_02_crisp_gif</code></td>
        #       <td>Generating high-definition GIFs with custom color palettes.</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Instant Lossless Trimming</strong></td>
        #       <td><code>.topic_03_lossless_cut</code></td>
        #       <td>Cutting clips in milliseconds with stream copy (-c copy).</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # ### Related Guides & Source References
        # - src/fluorite/presets/discord.cr
        # - src/fluorite/presets/gif.cr
        # - src/fluorite/presets/web.cr
        # - src/fluorite/presets/trim.cr
        #
        module CONVERSION_PRESETS
          # **Discord File Size Optimization**: Guaranteeing uploads fit under Discord limits without rejection.
          #
          # Discord rejects attachments exceeding upload limits (10MB, 25MB, or 50MB).
          # Fluorite's Discord preset queries duration via `ffprobe`, allocates total bits across video and audio,
          # and transcodes the video to guarantee it fits under the limit with maximal visual fidelity:
          # ```
          # Fluorite::Presets::Discord.convert("long_recording.mp4", "discord_upload.mp4", target_mb: 25.0)
          # ```
          #
          def self.topic_01_discord_budgeting : Nil; end

          # **2-Pass Palette GIF Generation**: Generating high-definition GIFs with custom color palettes.
          #
          # Standard GIF converters generate blurry, dithered artifacts.
          # Fluorite uses a 2-pass filtergraph generating a full 256-color palette with Lanczos scaling:
          # ```
          # Fluorite::Presets::Gif.convert("screen_record.mov", "demo.gif", fps: 15, width: 480)
          # ```
          #
          def self.topic_02_crisp_gif : Nil; end

          # **Instant Lossless Trimming**: Cutting clips in milliseconds with stream copy (-c copy).
          #
          # Cut any section of video without re-encoding:
          # ```
          # Fluorite::Presets::Trim.cut("movie.mp4", "clip.mp4", from: "00:01:30", to: "00:02:15")
          # ```
          #
          def self.topic_03_lossless_cut : Nil; end
        end
      end
    end
  end
{% end %}
