# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
  module Fluorite
    module Docs
      module E_TUI
        # # Interactive Terminal Studio and Wizard
        #
        # Fluorite integrates `sol-vin/opal` to deliver a terminal user experience inspired by professional video editing suites.
        # Users can navigate local media, inspect tracks and metadata, preview generated commands, and track real-time
        # encoding metrics with smooth progress bars and live logs.
        #
        # ### Executive Summary & Key Topics
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Topic</th>
        #       <th>Method / Anchor</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><strong>Launching the Studio</strong></td>
        #       <td><code>.topic_01_full_screen_tui</code></td>
        #       <td>Running the full-screen Opal terminal workspace.</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Step-by-Step CLI Wizard</strong></td>
        #       <td><code>.topic_02_interactive_wizard</code></td>
        #       <td>Prompt-driven conversion wizard.</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # ### Related Guides & Source References
        # - src/fluorite/tui/app.cr
        # - src/fluorite/cli.cr
        #
        module TUI_STUDIO
          # **Launching the Studio**: Running the full-screen Opal terminal workspace.
          #
          # Start the interactive TUI workspace:
          # ```bash
          # fluorite tui
          # # or simply:
          # fluorite
          # ```
          # Keybindings:
          # - `Tab`: Cycle between Media Files, Presets, and Streaming Logs.
          # - `↑` / `↓`: Navigate items in active pane.
          # - `Enter`: Start transcoding selected file with active preset.
          # - `C`: Copy the exact generated FFmpeg command to system clipboard.
          # - `R`: Refresh file list in current directory.
          # - `Q`: Quit.
          #
          def self.topic_01_full_screen_tui : Nil; end

          # **Step-by-Step CLI Wizard**: Prompt-driven conversion wizard.
          #
          # If you prefer an interactive questionnaire without entering full-screen mode:
          # ```bash
          # fluorite wizard
          # ```
          # This wizard guides you through selecting files, choosing goals, setting destination paths,
          # and confirming before running.
          #
          def self.topic_02_interactive_wizard : Nil; end
        end
      end
    end
  end
{% end %}
