# ==============================================================================
# Flourite::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Flourite
  # The `Flourite::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 5 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>GETTING_STARTED</code></td>
  #       <td><strong>Getting Started with Flourite</strong></td>
  #       <td>Introduction to Flourite modern FFMPEG library, fluent DSL, streaming runner, and interactive Opal TUI.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 2. Probe (`B_PROBE`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>MEDIA_PROBING</code></td>
  #       <td><strong>Deep Media Probing and Inspection</strong></td>
  #       <td>Extracting container metadata, codecs, stream specs, color spaces, and aspect ratios with ffprobe.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 3. Dsl (`C_DSL`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>FLUENT_DSL</code></td>
  #       <td><strong>Fluent Block and Chainable DSL</strong></td>
  #       <td>Authoring expressive FFmpeg pipelines using block-scoped and chainable Crystal builders.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 4. Presets (`D_PRESETS`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>CONVERSION_PRESETS</code></td>
  #       <td><strong>Smart Conversion Presets</strong></td>
  #       <td>Instant 1-line conversions for Discord file size fitting, crisp 2-pass GIFs, Web FastStart, and lossless stream cutting.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 5. Tui (`E_TUI`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>TUI_STUDIO</code></td>
  #       <td><strong>Interactive Terminal Studio and Wizard</strong></td>
  #       <td>Using the Opal full-screen reactive TUI and interactive CLI wizard for transcoding.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Flourite FFMPEG Toolkit Commands:
    # ```bash
    # flourite tui
    # flourite probe video.mp4
    # flourite discord video.mp4 --limit 25MB
    # flourite gif animation.mov --fps 15 --width 480
    # flourite wizard
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::GETTING_STARTED`: **Getting Started with Flourite** &mdash; Introduction to Flourite modern FFMPEG library, fluent DSL, streaming runner, and interactive Opal TUI.
    #
    # ##### 2. Probe (`B_PROBE`)
    # - `B_PROBE::MEDIA_PROBING`: **Deep Media Probing and Inspection** &mdash; Extracting container metadata, codecs, stream specs, color spaces, and aspect ratios with ffprobe.
    #
    # ##### 3. Dsl (`C_DSL`)
    # - `C_DSL::FLUENT_DSL`: **Fluent Block and Chainable DSL** &mdash; Authoring expressive FFmpeg pipelines using block-scoped and chainable Crystal builders.
    #
    # ##### 4. Presets (`D_PRESETS`)
    # - `D_PRESETS::CONVERSION_PRESETS`: **Smart Conversion Presets** &mdash; Instant 1-line conversions for Discord file size fitting, crisp 2-pass GIFs, Web FastStart, and lossless stream cutting.
    #
    # ##### 5. Tui (`E_TUI`)
    # - `E_TUI::TUI_STUDIO`: **Interactive Terminal Studio and Wizard** &mdash; Using the Opal full-screen reactive TUI and interactive CLI wizard for transcoding.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::GETTING_STARTED`: **Getting Started with Flourite** &mdash; Introduction to Flourite modern FFMPEG library, fluent DSL, streaming runner, and interactive Opal TUI.
    #
    # ##### `B_PROBE`
    # - `B_PROBE::MEDIA_PROBING`: **Deep Media Probing and Inspection** &mdash; Extracting container metadata, codecs, stream specs, color spaces, and aspect ratios with ffprobe.
    #
    # ##### `C_DSL`
    # - `C_DSL::FLUENT_DSL`: **Fluent Block and Chainable DSL** &mdash; Authoring expressive FFmpeg pipelines using block-scoped and chainable Crystal builders.
    #
    # ##### `D_PRESETS`
    # - `D_PRESETS::CONVERSION_PRESETS`: **Smart Conversion Presets** &mdash; Instant 1-line conversions for Discord file size fitting, crisp 2-pass GIFs, Web FastStart, and lossless stream cutting.
    #
    # ##### `E_TUI`
    # - `E_TUI::TUI_STUDIO`: **Interactive Terminal Studio and Wizard** &mdash; Using the Opal full-screen reactive TUI and interactive CLI wizard for transcoding.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/getting_started"
require "./docs/b_probe/media_probing"
require "./docs/c_dsl/fluent_dsl"
require "./docs/d_presets/conversion_presets"
require "./docs/e_tui/tui_studio"

alias FlouriteDocs = ::Flourite::Docs
{% end %}
